config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'

  resources :pins do
    member do
      put "like", to: "pins#upvote"
    end
  end
  devise_for :users
  root 'pins#index'

  get '/:id', to: 'profiles#show', as: :profile

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  acts_as_votable
  belongs_to :user
  has_attached_file :image, :styles => {:medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, length: { in: 2..12 }
  validates_uniqueness_of :name

  has_many :pins

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "https://s3.amazonaws.com/bw-pinclone/assets/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/vote.rb
class Vote < ActiveRecord::Base

  belongs_to :user
  belongs_to :pin
  validates_uniqueness_of :pin_id, scope: :user_id

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password, :avatar) }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :current_user, only: [:edit, :update, :destroy]
  before_action :set_pin, only: [:show, :edit, :update, :destroy, :upvote]

  def index
    @pins = Pin.all
  end
  def show
  end
  def new
    @pin = current_user.pins.build
  end
  def edit
  end
  def create
    @pin = current_user.pins.build(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  def update


    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Pin was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @pin.upvote_by current_user
    redirect_to :back
  end

  private
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def pin_params
      params.require(:pin).permit(:description, :image, :title, :name)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
      @user = User.find_by_name(params[:id])
      if @user
        @pins = @user.pins.all
        render action: :show
      else
        render file: 'public/404', status: 404, formats: [:html]
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/_header.html.erb
<div class="mobile-nav">
  <ul>
    <% if user_signed_in? %>
      <li><%= link_to "My Pins", profile_path(current_user.name) %></li>
      <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
      <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
      <li><%= link_to "New Pin", new_pin_path %></li>
    <% else %>
      <li><%= link_to "Log In", new_user_session_path %></li>
      <li><%= link_to "Sign Up", new_user_registration_path %><li>
    <% end %>
  </ul>
</div>
<header>
  <div class="header-position">
    <div class="logo">
      <%= link_to "pinclone", root_path %>
    </div>
    <% if user_signed_in? %>
      <div class="new-pin-btn"><%= link_to "New Pin", new_pin_path %></div>
    <% end %>
    <div class="site-nav">
      <ul>
        <% if user_signed_in? %>
          <li><%= link_to "My Pins", profile_path(current_user.name) %></li>
          <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
          <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
        <% else %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %><li>
        <% end %>
      </ul>
    </div>
    <div class="mobile-nav-toggle"><span></span></div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinclone</title>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class="home-wrap">
    <%=  render "layouts/header" %>
    <div class="home-sections">
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert")%>
      <% end %>
      <%= yield %>
    </div>
  </div>
<script>
  $(document).ready(function(){
    setTimeout(function(){
      $('.alert').fadeOut("slow", function(){
        $this.remove();
      })
    }, 2500);
  });
</script>
</body>
</html>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div class="actions user-btn-main">
    <%= f.submit %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<div class="user-wrap">
  <div class="user-form">
    <h2>Edit Pin</h2>
    <%= render 'form' %>
    <div class="user-btn-shared">
      <%= link_to 'Show', @pin %> |
      <%= link_to 'Back', pins_path %>
    </div>
  </div>
</div>

app/views/pins/index.html.erb
<div id="all-pins" class="transitions-enabled">
    <% @pins.reverse_each do |pin| %>
    <div class="box">
      <div class="edit-image"><%= link_to image_tag(pin.image.url), pin_path(pin) %>
        <div class="pin-edit">
          <% if pin.user == current_user %>
            <%= link_to edit_pin_path(pin) do %>
              <i class="fa fa-pencil-square-o"></i>
            <% end %>
            <%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <i class="fa fa-trash-o"></i>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="box-body">
        <h1><%= pin.title %></h1>
        <h2><%= pin.description %></h2>
      </div>
      <hr>
      <div class="box-body">
        <div class="avatar">
          <% if pin.user == current_user %>
            <%= link_to image_tag(current_user.avatar.url(:thumb)), edit_user_registration_path %>
          <% else %>
            <%= link_to image_tag(pin.user.avatar.url(:thumb)), profile_path(pin.user.name) %>
          <% end %>
        </div>
        <p>by <span><%=link_to pin.user.name, profile_path(pin.user.name) %></span><p>
      </div>
    </div>
  <% end %>
</div>

app/views/pins/new.html.erb
<div class="user-wrap">
  <div class="user-form">
    <h2>New Pin</h2>
    <%= render 'form' %>
    <div class="user-btn-shared">
      <%= link_to 'Back', :back %>
    </div>
  </div>
</div>

app/views/pins/show.html.erb
<div class="user-wrap">
  <div class="user-show">
    <%= image_tag @pin.image.url %>
    <h3><%= @pin.title %></h3>
    <h4><%= @pin.description %></h4>
    <p>by <span><%= link_to @pin.user.name, profile_path(@pin.user.name) if @pin.user %></span><p>
    <%= link_to like_pin_path(@pin), method: :put do |u| %>
      <div class="vote"><i class="fa fa-heart"></i> <%= @pin.get_upvotes.size %></div>
    <% end %>
    <div class="user-btn-shared">
      <% if @pin.user == current_user %>
        <%= link_to 'Edit', edit_pin_path(@pin) %> |
      <% end %>
      <%= link_to 'Back', :back %>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<div id="all-pins" class="transitions-enabled">
  <div class="box box-user">
    <div class="avatar"><%= image_tag(@user.avatar.url(:thumb)) %></div>
    <h1><%= @user.name %></h1>
    <h3>My Pins</h3>
  </div>
  <% if @user == current_user %>
    <div class="box new-pin">
      <h5><%= link_to new_pin_path do %><i class="fa fa-plus-circle"></i><% end %></h5>
    </div>
  <% end %>
  <% if @pins %>
    <% @pins.reverse_each do |pin| %>
      <div class="box">
        <div class="edit-image"><%= link_to image_tag(pin.image.url), pin_path(pin) %>
          <div class="pin-edit">
            <% if pin.user == current_user %>
              <%= link_to edit_pin_path(pin) do %>
                <i class="fa fa-pencil-square-o"></i>
              <% end %>
              <%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
                <i class="fa fa-trash-o"></i>
              <% end %>
            <% end %>
          </div>
          <div class="box-body">
            <h1><%= pin.title %></h1>
            <h2><%= pin.description %></h2>
          </div>
          <div class="box-body">
            <%= link_to like_pin_path(pin), method: :put do |u| %>
              <div class="vote"><i class="fa fa-heart"></i> <%= pin.get_upvotes.size %></div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>